### ISSUE TITLE
不知道大佬看不看

### ISSUE THREAD

**Issue by huangguabaizhan** [waifu-project/18comic#10]
最近禁漫更新了反扒手段导致18app图片错位了，能不能更新一下。拜托了。

**Comment by DogFather** [comment]
凉了呀

**Comment by d1y** [comment]
> 最近禁漫更新了反扒手段导致18app图片错位了，能不能更新一下。拜托了。

有截图吗, 让我康康是什么问题

**Comment by huangguabaizhan** [comment]
![Uploading Screenshot_20201112-211958_18comic.jpg…]()

**Comment by huangguabaizhan** [comment]
![Screenshot_20201112-211958_18comic](https://user-images.githubusercontent.com/64844235/98945177-1cb03c80-252d-11eb-8151-ab6c28d671be.jpg)

**Comment by huangguabaizhan** [comment]
就是这样，好像是反扒

**Comment by huangguabaizhan** [comment]
![Screenshot_20201112-212311_18comic](https://user-images.githubusercontent.com/64844235/98945298-4bc6ae00-252d-11eb-9970-1d04d04260b0.jpg)

**Comment by d1y** [comment]
确实是反扒, 我研究下

**Comment by huangguabaizhan** [comment]
谢谢您

**Comment by xueyuan1126** [comment]
为什么ios的下载不了？程序标总是黑的显示无法安装😭

**Comment by Battesla** [comment]
老哥，不能用了，图折叠了。

**Comment by lolp521** [comment]
我这里也是这个问题，求大佬解决。

**Comment by d1y** [comment]
jm现在有官方app了，体验良好，推荐使用官方app🙄

**Comment by 1126107509** [comment]
每个图片折叠次数不一样，，有没有哪位大佬解决一下
