### ISSUE TITLE
基于Android11的miui12.5的小米10pro打开app直接白屏, 无法显示主页面

### ISSUE THREAD

**Issue by jiayaoO3O** [waifu-project/18comic#19]
1. 安装包版本是20200901的__UNI__4D582C0_0831211944.apk
2. 已经使用代理
3. 打开app之后可以显示底栏, 但是程序主界面是一片空白的
![image](https://user-images.githubusercontent.com/22891632/107956574-47051080-6fda-11eb-98ce-de0be6856d95.png)

**Comment by ozmango2020** [comment]
我也是
