### ISSUE TITLE
安卓版所有界面空白

### ISSUE THREAD

**Issue by lolisaikou** [waifu-project/18comic#2]
在手机（安卓10，miui12）和模拟器（mumu）上全部页面空白
全程梯子，存储权限也给了
![image](https://user-images.githubusercontent.com/32028165/85029114-83b00c00-b1ae-11ea-95dc-3920459f9677.png)

**Comment by d1y** [comment]
:bug: 确实有问题, 在 `ios` 是好好的, 我看下是啥问题, 感谢提的 `issues`

**Comment by zhuwenbing** [comment]
一样也是Android 10，我还以为是我梯子坏了，哈哈

**Comment by d1y** [comment]
抱歉, 各位, 这两天一直在找解决方案, 去 `uniapp` 官方提了 `issues`, 但是还是解决不了, 
本来打算还继续加功能的, 现在已经弃坑了

)已经在用 `flutter` 重写了
