### ISSUE TITLE
这里这里, 常见问题问答(FAQ)

### ISSUE THREAD

**Issue by d1y** [waifu-project/18comic#4]
## 这和 `bika` 有什么联系和区别?

实际上, 我在做的时候, 参照就是 `bika`, 甚至连 `ui` 都抄的一毛一样(现在有亿点点不同了), 但是接口不是 `bika` 的, 而是 **禁漫天堂**  的.

## 根本用不了啊?

如果不是闪退或者其他类的话, 单纯网络问题的话, 由于网络的封锁, 镜像站基本上被封了, 所以, 如果你想用的话

1. 开 `vpn`, 然后走主站
2. 试一下分流站

那怎么切换镜像站呢?

点击 `设置>版本号` 10次, 找到 `开发者相关>路由菜单列表` 选择 `views/switch/flow` 切换镜像站

**Comment by Minidoracat** [comment]
請問已經不維護了嗎?
下載下來運行有報錯
說明頁面的releases鏈結也錯了
本來很想試試看大佬寫的神器呢

`
ERROR in F:/github/18comic/src/utils/index.ts(44,10):
44:10 Expected 1 arguments, but got 0.
    42 |       query.select(ele).boundingClientRect((data: any)=> {
    43 |         res(data)
  > 44 |       }).exec()
       |          ^
    45 |     }))
    46 |     return new Promise(async res=> {
    47 |       let result: any = null
ERROR in F:/github/18comic/src/utils/index.ts(142,22):
142:22 Argument of type '{ delta: number; }' is not assignable to parameter of type 'NavigateBackOptions'.
  Type '{ delta: number; }' is missing the following properties from type 'NavigateBackOptions': animationType, animationDuration
    140 |   },
    141 |   back(delta: number = 1) {
  > 142 |     uni.navigateBack({ delta })
        |                      ^
    143 |   },
    144 |   redirect(url: string) {
    145 |     uni.redirectTo({ url: `/views/${ url }` })
ERROR in F:/github/18comic/src/views/detail/index.vue(207,29):
207:29 Argument of type '{ type: "text"; summary: string; href: string; }' is not assignable to parameter of type 'ShareWithSystemOptions'.
  Property 'imageUrl' is missing in type '{ type: "text"; summary: string; href: string; }' but required in type 'ShareWithSystemOptions'.
    205 |         const id = this.id || ""
    206 |         let href = `${ api }/album/${ id }`
  > 207 |         uni.shareWithSystem({
        |                             ^
    208 |           type: 'text',
    209 |           summary: this.data.title || "",
    210 |           href
`

**Comment by d1y** [comment]
你好 这个问题已经修复了，在 dev 分支，并且也修复了部分的bug

本来确实准备转到flutter，无奈电脑配置太渣，所以继续使用 uniapp

事实上这只是bika的替代品，现在哔咔ios不更新了，所以，自给自足

暂时不会弃坑，学生党时间还是比较充裕

以上

**Comment by LetHergo** [comment]
提问：作者身体还好吗

**Comment by d1y** [comment]
> 提问：作者身体还好吗

发生肾么事了

![image](https://user-images.githubusercontent.com/45585937/98818642-ce386a80-2466-11eb-8adb-d895693fa9ef.png)

**Comment by 442941785** [comment]
用不了啊，一直读不出来，萌新也不会挂vpn

**Comment by d1y** [comment]
> 用不了啊，一直读不出来，萌新也不会挂vpn

中国联通表示可以用, 不知道你尝试切换镜像没

**Comment by 442941785** [comment]
> > 用不了啊，一直读不出来，萌新也不会挂vpn
> 
> 中国联通表示可以用, 不知道你尝试切换镜像没

网络是中国移动，镜像都切换过了都不行

**Comment by Battesla** [comment]
老哥，不能用了，图折叠了。

**Comment by 1965709765** [comment]
请问漫画大多数图片顺序都是乱的怎么解决

**Comment by lzs222** [comment]
话说VPN怎么弄啊
