### ISSUE TITLE
關於IOS問題

### ISSUE THREAD

**Issue by Minidoracat** [waifu-project/18comic#6]
請問目前ipa裝上去只會變成iPhone版本的嗎?
我使用AltStore安裝後到iPad後，只會變成iPhone版，放大後左右還是會有黑框
請問是因為目前格式只支援iPhone嗎?

**Comment by d1y** [comment]
我并没有苹果家的开发经验, 手上米有 `ipad`, 所以在下暂时不会适配 `ipad` 版本 )逃

**Comment by d1y** [comment]
@Minidoracat 重新打了一个包, 这回应该 `ipad` 没有黑框了🌝

https://d1y.lanzous.com/ih1Ksf58ozc

**Comment by Minidoracat** [comment]
> @Minidoracat 重新打了一个包, 这回应该 `ipad` 没有黑框了🌝
> 
> https://d1y.lanzous.com/ih1Ksf58ozc

感謝大佬!馬上來試試看
